name: Publish docker image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "PACKAGE_JSON=$(jq -c . < ./packages/mcp/package.json)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/runner.Dockerfile
          build-args: |
            PKG_VER=${{ fromJson(env.PACKAGE_JSON).version }}
          push: true
          tags: |
            woodenfish42/tiny-tool-browser-mcp:${{ github.event.inputs.version }}
