name: Publish docker image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PACKAGE_JSON=$(jq -c . < ./packages/mcp/package.json)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          file: docker/runner.Dockerfile
          build-args: |
            PKG_VER=${{ fromJson(env.PACKAGE_JSON).version }}
          push: true
          tags: |
            tinytool/browser-mcp:${{ fromJson(env.PACKAGE_JSON).version }}
            ghcr.io/${{ github.repository }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
